image:
  name: quay.io/alantang888/k8s-old-pod-killer
  tag: 1.0.1
  pullPolicy: Always

extraLabel: {}

config:
  dryrun: false
  batch_mode: false
  default_interval: 10m
  targets: []
  # example
  # - kind: deployment
  #   name_space: just-a-dummy-example
  #   name: just-a-dummy-example
  #   max_life: "99999999h"
  #   interval: "99999999h"
  #   batch_max_kill: 1
